/* ============================================
   EMBERS OF US — Student Data
   60 students with farewell messages
   ============================================ */

window.STUDENTS = [
    { name: "Aarav Sharma", title: "Every late night in the lab was worth it — because you all were there.", message: "The quiet one who fixed everyone's bugs at 2 AM." },
    { name: "Ananya Patel", title: "I came here to learn code. I leave knowing what friendship compiles into.", message: "She turned coffee into courage and deadlines into dreams." },
    { name: "Arjun Mehta", title: "Remember the rooftop talks? That's the memory I'm keeping forever.", message: "Always had a plan B. And a plan C. And a plan D." },
    { name: "Diya Nair", title: "We didn't just share notes — we shared pieces of who we are.", message: "The voice of reason in every group project storm." },
    { name: "Kabir Verma", title: "Three years felt like three weeks. I wish I'd slowed down.", message: "He made even Monday mornings feel survivable." },
    { name: "Ishita Reddy", title: "If college was a function, you all were the return value.", message: "The one who always asked 'but why?' — and found the answer." },
    { name: "Rohan Desai", title: "I'll miss the chaos. The beautiful, irreplaceable chaos.", message: "Class clown by day, silent poet by night." },
    { name: "Meera Iyer", title: "Some bonds don't need WiFi. Ours was always connected.", message: "She could debug your code and your mood in one sitting." },
    { name: "Vivaan Joshi", title: "We wrote our story in semicolons and sleepless nights.", message: "The friend who'd stay back just so you didn't walk alone." },
    { name: "Priya Kulkarni", title: "This isn't goodbye. It's just a different kind of hello.", message: "Her laughter echoed louder than any lecture hall." },
    { name: "Aditya Rao", title: "The canteen, the corridor, the last bench — I'll carry it all.", message: "He never topped the class, but he topped every heart." },
    { name: "Sneha Bose", title: "You made the hard days soft and the good days unforgettable.", message: "The calm before, during, and after every storm." },
    { name: "Karan Singh", title: "Here's to the ones who made failure feel like a group activity.", message: "His confidence was contagious, even when misplaced." },
    { name: "Riya Gupta", title: "I didn't find my career here. I found my people.", message: "She planned every event and still showed up to all of them." },
    { name: "Nikhil Pandey", title: "Some of the best algorithms were the ones we never submitted.", message: "Thought out loud, lived out louder." },
    { name: "Tanya Kapoor", title: "College gave me a degree. You all gave me a home.", message: "The first to cry, the first to laugh, the last to leave." },
    { name: "Sahil Malhotra", title: "If memories had a runtime, ours would never terminate.", message: "He turned every gathering into a celebration." },
    { name: "Pooja Menon", title: "Thank you for being my constants in a world full of variables.", message: "Quiet strength wrapped in warm smiles." },
    { name: "Dev Chauhan", title: "We debugged life together. That's more than enough.", message: "The one who always had an extra charger." },
    { name: "Nandini Saxena", title: "These walls heard our dreams before the world ever will.", message: "Dreamer with a to-do list longer than any syllabus." },
    { name: "Aryan Thakur", title: "I'll miss arguing about tabs vs spaces with you lot.", message: "Strong opinions, stronger friendships." },
    { name: "Kavya Pillai", title: "We came as strangers and leave as stories in each other's lives.", message: "She wrote poetry in the margins of her notebooks." },
    { name: "Rahul Agarwal", title: "The presentations were scary. But never with you beside me.", message: "Nervous speaker, natural leader." },
    { name: "Anjali Dubey", title: "Every 'see you tomorrow' was a promise we kept for three years.", message: "The glue that held every friend group together." },
    { name: "Manav Sethi", title: "I hope life has the same energy as our WhatsApp group at 3 AM.", message: "Meme lord. Emotional support human." },
    { name: "Simran Kaur", title: "We didn't just attend lectures — we built a universe.", message: "Fierce, gentle, and impossibly kind." },
    { name: "Harsh Tiwari", title: "Our friendship compiled without a single error.", message: "He believed in everyone more than they believed in themselves." },
    { name: "Ritika Jain", title: "The library was our sanctuary. You were my peace.", message: "Found clarity between the pages and the people." },
    { name: "Varun Bhatt", title: "Three years, one batch, infinite inside jokes.", message: "Walking encyclopedia with a comedian's timing." },
    { name: "Shruti Mishra", title: "I'm grateful for every unplanned detour we took together.", message: "Spontaneous soul with a structured mind." },
    { name: "Aakash Rajput", title: "We were the generation that coded dreams into reality.", message: "Big ideas, bigger heart, biggest smile." },
    { name: "Neha Srivastava", title: "Every group photo is a timestamp of pure joy.", message: "She remembered every birthday and every broken heart." },
    { name: "Pranav Gokhale", title: "The real project was the friendship we built along the way.", message: "Silent contributor, loudest impact." },
    { name: "Divya Chatterjee", title: "You taught me that the best code is written with people you love.", message: "Danced through deadlines like they were music." },
    { name: "Siddharth Nair", title: "These corridors will miss our footsteps. I know I will.", message: "Walked slow, thought fast, loved deeply." },
    { name: "Fatima Sheikh", title: "In a room full of logic, you all were my favorite emotion.", message: "Her kindness was the algorithm everyone needed." },
    { name: "Yash Patil", title: "We shared more than a batch number. We shared a heartbeat.", message: "The friend who'd cancel plans just to be there for you." },
    { name: "Aditi Banerjee", title: "I'll remember the laughter between the lectures most of all.", message: "She found sunshine in syntax errors." },
    { name: "Kunal Deshpande", title: "You didn't just make college bearable — you made it legendary.", message: "Class representative, chaos coordinator." },
    { name: "Swati Rawat", title: "Our playlist was longer than our syllabus. Worth it.", message: "The one with the perfect song for every mood." },
    { name: "Omkar Mane", title: "These three years? Best runtime of my life.", message: "Cricket enthusiast, accidental philosopher." },
    { name: "Bhavna Hegde", title: "Every assignment submission was a group therapy session.", message: "She made stress look graceful." },
    { name: "Jayesh Dalal", title: "I'll carry your voices in my head like background music.", message: "Quiet in class, unstoppable outside." },
    { name: "Lakshmi Venkatesh", title: "Some things can't be version-controlled. Like what we shared.", message: "Old soul in a young world." },
    { name: "Mihir Gandhi", title: "We were each other's Stack Overflow — always had the answer.", message: "Problem solver by nature, friend by choice." },
    { name: "Zara Khan", title: "Thank you for making me feel like I belonged — every single day.", message: "The warmth in every cold morning lecture." },
    { name: "Tejas Kulkarni", title: "From 'Hello World' to 'Goodbye World' — what a journey.", message: "First to arrive, last to log off." },
    { name: "Charvi Sinha", title: "The viva was tough but your support was tougher.", message: "Grace under pressure, beauty under chaos." },
    { name: "Akshay Pawar", title: "Every error we fixed together made us stronger apart.", message: "He debugged life with patience and chai." },
    { name: "Madhavi Rane", title: "I didn't just earn a degree — I earned a family.", message: "Motherly, fierce, and unforgettable." },
    { name: "Rajat Khanna", title: "To late submissions and lasting friendships — cheers.", message: "Procrastinator who always delivered when it mattered." },
    { name: "Isha Choudhary", title: "We made memories that no hard drive could ever store.", message: "Ambitious dreamer with ink-stained fingers." },
    { name: "Gaurav Wagh", title: "This campus was our playground. You were my team.", message: "Team player in every sense of the word." },
    { name: "Pallavi Jog", title: "You gave meaning to every moment I almost gave up.", message: "She listened when the world was too loud." },
    { name: "Avinash Shetty", title: "If nostalgia had a face, it would look like our classroom.", message: "Gentle giant with a voice like home." },
    { name: "Sonal Trivedi", title: "We were parallel processes running the same beautiful program.", message: "Organized chaos personified." },
    { name: "Rohit More", title: "No API can fetch what we shared. It was one of a kind.", message: "Backend thinker, frontend feeler." },
    { name: "Tanvi Parikh", title: "These stars in the sky? They remind me of all of you.", message: "She saw constellations where others saw dots." },
    { name: "Mayank Bajaj", title: "We didn't just graduate — we evolved, together.", message: "He grew taller in spirit than in stature." },
    { name: "Radhika Sane", title: "Every ending is just a commit to a new branch. See you there.", message: "The last star to fade, but never to disappear." }
];
